// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATiL5r3_OGkv-FCZGBGm_fLSh4SHS3e24',
    appId: '1:696055684676:web:c9df53e7cb22fff32b2611',
    messagingSenderId: '696055684676',
    projectId: 'chatapp-309bf',
    authDomain: 'chatapp-309bf.firebaseapp.com',
    storageBucket: 'chatapp-309bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEaFZp6W5R1g3T_8m7zpN1Oaj1zBNFC4c',
    appId: '1:696055684676:android:25510157237e0fb22b2611',
    messagingSenderId: '696055684676',
    projectId: 'chatapp-309bf',
    storageBucket: 'chatapp-309bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNSaUKvu7aAxYZyrKAg0GWkEtXxV7qX6w',
    appId: '1:696055684676:ios:40e49b469d40e2b92b2611',
    messagingSenderId: '696055684676',
    projectId: 'chatapp-309bf',
    storageBucket: 'chatapp-309bf.firebasestorage.app',
    iosBundleId: 'com.example.quickChat',
  );
}
